App\Api\Chauffage\Model\Emetteur:
  attributes:
    id:
      groups: ["read", "write"]
    description:
      groups: ["read", "write"]
    type:
      groups: ["read", "write"]
    temperature_distribution:
      groups: ["read", "write"]
    presence_robinet_thermostatique:
      groups: ["read", "write"]
    annee_installation:
      groups: ["read", "write"]
