api_platform:
    title: Moteur DPE-Audit
    version: 1.0.0
    show_webby: false
    mapping:
        paths: ["%kernel.project_dir%/config/api"]
    formats:
        json: ["application/json"]
        jsonld: ["application/ld+json"]
        jsonpatch: ["application/merge-patch+json"]
    patch_formats:
        json: ["application/merge-patch+json"]
    defaults:
        stateless: true
        normalization_context:
            skip_null_values: false
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
