App\Api\Ecs\Model\Generateur:
  attributes:
    id:
      groups: ["read", "write"]
    description:
      groups: ["read", "write"]
    type:
      groups: ["read", "write"]
    energie:
      groups: ["read", "write"]
    volume_stockage:
      groups: ["read", "write"]
    generateur_collectif:
      groups: ["read", "write"]
    position_volume_chauffe:
      groups: ["read", "write"]
    annee_installation:
      groups: ["read", "write"]
    pn:
      groups: ["read", "write"]
    cop:
      groups: ["read", "write"]
    label:
      groups: ["read", "write"]
    type_chaudiere:
      groups: ["read", "write"]
    mode_combustion:
      groups: ["read", "write"]
    presence_ventouse:
      groups: ["read", "write"]
    pveilleuse:
      groups: ["read", "write"]
    qp0:
      groups: ["read", "write"]
    rpn:
      groups: ["read", "write"]
    reseau_chaleur_id:
      groups: ["read", "write"]
    generateur_mixte_id:
      groups: ["read", "write"]
    data:
      groups: ["read"]

App\Api\Ecs\Model\GenerateurData:
  attributes:
    pecs:
      groups: ["read"]
    paux:
      groups: ["read"]
    pn:
      groups: ["read"]
    cop:
      groups: ["read"]
    rpn:
      groups: ["read"]
    qp0:
      groups: ["read"]
    pveilleuse:
      groups: ["read"]
    pertes:
      groups: ["read"]
    pertes_recuperables:
      groups: ["read"]
    consommations:
      groups: ["read"]
    emissions:
      groups: ["read"]
