App\Api\Ecs\Model\Installation:
  attributes:
    id:
      groups: ["read", "write"]
    description:
      groups: ["read", "write"]
    surface:
      groups: ["read", "write"]
    solaire_thermique:
      groups: ["read", "write"]
    data:
      groups: ["read"]

App\Api\Ecs\Model\InstallationData:
  attributes:
    rdim:
      groups: ["read"]
    fecs:
      groups: ["read"]
    pertes:
      groups: ["read"]
    pertes_recuperables:
      groups: ["read"]
    consommations:
      groups: ["read"]
    emissions:
      groups: ["read"]

App\Api\Ecs\Model\Solaire:
  attributes:
    usage:
      groups: ["read", "write"]
    annee_installation:
      groups: ["read", "write"]
    fecs:
      groups: ["read", "write"]
