App\Api\Enveloppe\Model\Porte:
  attributes:
    id:
      groups: ["read", "write"]
    description:
      groups: ["read", "write"]
    type_pose:
      groups: ["read", "write"]
    isolation:
      groups: ["read", "write"]
    materiau:
      groups: ["read", "write"]
    presence_sas:
      groups: ["read", "write"]
    annee_installation:
      groups: ["read", "write"]
    u:
      groups: ["read", "write"]
    position:
      groups: ["read", "write"]
    vitrage:
      groups: ["read", "write"]
    menuiserie:
      groups: ["read", "write"]
    data:
      groups: ["read"]

App\Api\Enveloppe\Model\Porte\Data:
  attributes:
    sdep:
      groups: ["read"]
    u:
      groups: ["read"]
    b:
      groups: ["read"]
    dp:
      groups: ["read"]
    isolation:
      groups: ["read"]
    performance:
      groups: ["read"]

App\Api\Enveloppe\Model\Porte\Menuiserie:
  attributes:
    largeur_dormant:
      groups: ["read", "write"]
    presence_joint:
      groups: ["read", "write"]
    presence_retour_isolation:
      groups: ["read", "write"]

App\Api\Enveloppe\Model\Porte\Position:
  attributes:
    paroi_id:
      groups: ["read", "write"]
    local_non_chauffe_id:
      groups: ["read", "write"]
    surface:
      groups: ["read", "write"]
    orientation:
      groups: ["read", "write"]
    mitoyennete:
      groups: ["read", "write"]

App\Api\Enveloppe\Model\Porte\Vitrage:
  attributes:
    taux_vitrage:
      groups: ["read", "write"]
    type_vitrage:
      groups: ["read", "write"]
