App\Api\Refroidissement\Model\Installation:
  attributes:
    id:
      groups: ["read", "write"]
    description:
      groups: ["read", "write"]
    surface:
      groups: ["read", "write"]
    data:
      groups: ["read"]

App\Api\Refroidissement\Model\InstallationData:
  attributes:
    rdim:
      groups: ["read"]
    consommations:
      groups: ["read"]
    emissions:
      groups: ["read"]
