App\Api\Refroidissement\Model\Refroidissement:
  attributes:
    id:
      groups: ["read"]
    generateurs:
      groups: ["read", "write"]
    installations:
      groups: ["read", "write"]
    systemes:
      groups: ["read", "write"]
    data:
      groups: ["read"]

App\Api\Refroidissement\Model\RefroidissementData:
  attributes:
    besoins:
      groups: ["read"]
    consommations:
      groups: ["read"]
    emissions:
      groups: ["read"]
