App\Api\Refroidissement\Model\Systeme:
  attributes:
    id:
      groups: ["read", "write"]
    installation_id:
      groups: ["read", "write"]
    generateur_id:
      groups: ["read", "write"]
    data:
      groups: ["read"]

App\Api\Refroidissement\Model\SystemeData:
  attributes:
    rdim:
      groups: ["read"]
    consommations:
      groups: ["read"]
    emissions:
      groups: ["read"]
