App\Api\Eclairage\Model\Eclairage:
  attributes:
    data:
      groups: ["read"]

App\Api\Eclairage\Model\EclairageData:
  attributes:
    consommations:
      groups: ["read"]
    emissions:
      groups: ["read"]
