resources:
  App\Domain\Audit\Audit:
    shortName: Audit
    operations:
      audit.get:
        uriTemplate: /audit/{id}
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Audit\State\AuditProvider
        output: App\Api\Audit\Resource\AuditResource
