resources:
  App\Api\Audit\Model\Audit:
    shortName: Audit
    normalizationContext:
      groups: ["read"]
    denormalizationContext:
      groups: ["write"]
    operations:
      audit.get:
        uriTemplate: /audit/{id}
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Audit\State\AuditProvider
      audit.post:
        uriTemplate: /audit
        class: ApiPlatform\Metadata\Post
        processor: App\Api\Audit\State\AuditProcessor
