resources:
  App\Domain\Audit\Audit:
    shortName: Audit
    operations:
      audit.get:
        class: ApiPlatform\Metadata\Get
        uriTemplate: /audit/{id}
        output: App\Api\Audit\Resource\AuditResource
