resources:
  App\Domain\Chauffage\Chauffage:
    shortName: Chauffage
    operations:
      chauffage.get:
        uriTemplate: /audit/{id}/chauffage
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Chauffage\State\ChauffageProvider
        output: App\Api\Chauffage\Resource\ChauffageResource
