resources:
  App\Api\Chauffage\Model\Chauffage:
    shortName: Chauffage
    normalizationContext:
      groups: ["read"]
    denormalizationContext:
      groups: ["write"]
    operations:
      chauffage.get:
        uriTemplate: /audit/{id}/chauffage
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Chauffage\State\ChauffageProvider
