resources:
  App\Domain\Chauffage\Chauffage:
    operations:
      chauffage.get:
        class: ApiPlatform\Metadata\Get
        uriTemplate: /audit/{id}/chauffage
        output: App\Api\Chauffage\Resource\ChauffageResource

