resources:
  App\Api\Ecs\Model\Ecs:
    shortName: Ecs
    normalizationContext:
      groups: ["read"]
    denormalizationContext:
      groups: ["write"]
    operations:
      ecs.get:
        uriTemplate: /audit/{id}/ecs
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Ecs\State\EcsProvider
