resources:
  App\Api\Ecs\Model\Ecs:
    shortName: Ecs
    operations:
      ecs.get:
        uriTemplate: /audit/{id}/ecs
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Ecs\State\EcsProvider
