resources:
  App\Api\Ecs\Model\Ecs:
    shortName: Ecs
    collectDenormalizationErrors: true
    normalizationContext:
      groups: ["read"]
    denormalizationContext:
      groups: ["write"]
    operations:
      ecs.get:
        uriTemplate: /audit/{id}/ecs
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Ecs\State\EcsProvider
        controller: ApiPlatform\Symfony\Action\NotFoundAction
        openapi:
          summary: 🚧 Retourne les données d'eau chaude sanitaire d'un audit énergétique
          description: |
            **Disponible après syncrhonisation avec les données de l'observatoire DPE-Audit**
