resources:
  App\Api\Enveloppe\Model\Enveloppe:
    shortName: Enveloppe
    operations:
      enveloppe.get:
        uriTemplate: /audit/{id}/enveloppe
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Enveloppe\State\EnveloppeProvider
