resources:
  App\Api\Enveloppe\Model\Enveloppe:
    shortName: Enveloppe
    collectDenormalizationErrors: true
    normalizationContext:
      groups: ["read"]
    denormalizationContext:
      groups: ["write"]
    operations:
      enveloppe.get:
        uriTemplate: /audit/{id}/enveloppe
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Enveloppe\State\EnveloppeProvider
        controller: ApiPlatform\Symfony\Action\NotFoundAction
        openapi:
          summary: 🚧 Retourne les données de l'enveloppe d'un audit énergétique
          description: |
            **Disponible après syncrhonisation avec les données de l'observatoire DPE-Audit**
