resources:
  App\Domain\Enveloppe\Enveloppe:
    shortName: Enveloppe
    operations:
      enveloppe.get:
        uriTemplate: /audit/{id}/enveloppe
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Enveloppe\State\EnveloppeProvider
        output: App\Api\Enveloppe\Resource\EnveloppeResource
