resources:
  App\Domain\Production\Production:
    shortName: Production
    operations:
      production.get:
        uriTemplate: /audit/{id}/production
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Production\State\ProductionProvider
        output: App\Api\Production\Resource\ProductionResource
