resources:
  App\Api\Production\Model\Production:
    shortName: Production
    normalizationContext:
      groups: ["read"]
    denormalizationContext:
      groups: ["write"]
    operations:
      production.get:
        uriTemplate: /audit/{id}/production
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Production\State\ProductionProvider
