resources:
  App\Api\Refroidissement\Model\Refroidissement:
    shortName: Refroidissement
    operations:
      refroidissement.get:
        uriTemplate: /audit/{id}/refroidissement
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Refroidissement\State\RefroidissementProvider
