resources:
  App\Domain\Refroidissement\Refroidissement:
    shortName: Refroidissement
    operations:
      refroidissement.get:
        uriTemplate: /audit/{id}/refroidissement
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Refroidissement\State\RefroidissementProvider
        output: App\Api\Refroidissement\Resource\RefroidissementResource
