resources:
  App\Api\Ventilation\Model\Ventilation:
    shortName: Ventilation
    normalizationContext:
      groups: ["read"]
    denormalizationContext:
      groups: ["write"]
    operations:
      ventilation.get:
        uriTemplate: /audit/{id}/ventilation
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Ventilation\State\VentilationProvider
