resources:
  App\Domain\Ventilation\Ventilation:
    shortName: Ventilation
    operations:
      ventilation.get:
        uriTemplate: /audit/{id}/ventilation
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Ventilation\State\VentilationProvider
        output: App\Api\Ventilation\Resource\VentilationResource
