resources:
  App\Api\Ventilation\Model\Ventilation:
    shortName: Ventilation
    operations:
      ventilation.get:
        uriTemplate: /audit/{id}/ventilation
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Ventilation\State\VentilationProvider
