resources:
  App\Domain\Ventilation\Ventilation:
    operations:
      ventilation.get:
        class: ApiPlatform\Metadata\Get
        uriTemplate: /audit/{id}/ventilation
        output: App\Api\Ventilation\Resource\VentilationResource
