resources:
  App\Domain\Visite\Visite:
    shortName: Visite
    operations:
      visite.get:
        uriTemplate: /audit/{id}/visite
        class: ApiPlatform\Metadata\Get
        provider: App\Api\Visite\State\VisiteProvider
        output: App\Api\Visite\Resource\VisiteResource
